### ISSUE TITLE
Report function and 

### ISSUE THREAD

**Issue by GregorDall** [Biometris/statgenSTA#5]
I would like to generate a report from my model, but I get the following error, even if I set a path like D:\Test.pdf on windows or /home/user/Test.pdf on Ubuntu. I am running out of ideas. 
Best Gregor

Error in createReport(x = modTr, reportName = "modelReport.Rnw", reportPackage = "statgenSTA",  :    outfile path cannot contain spaces. Provide a path without spaces or a relative path.

**Comment by BartJanvanRossum** [comment]
Could you try to run the code below. That should fit a very basic model and then create a report for it in a temporary directory. If this works without errors, could you then please show me the exact call you use when you try to create your own report. 

One other thing, for Windows, the path should be "D:/Test.pdf", so with /, instead of \. However I think you already got that correct, otherwise you would get a different error message.

```r
library(statgenSTA)

modLme <- fitTD(TD = TDHeat05,
                design = "ibd",
                traits = "yield",
                engine = "lme4")

report(modLme,
       outfile = tempfile(fileext = ".pdf"),
       what = "fixed")
}

```

**Comment by GregorDall** [comment]
Thank your, your code runs and produces a pdf. This is my attempt, which does not:

temp <- createTD(data = pheno,
          genotype = "PG", 
           year = "year",
           trial = "trial",
            repId = "rep", 
            checkId = "standard",
            # subBlock = "BLOCK",
            rowCoord = "row", 
            colCoord = "column")
   mymod <- fitTD(TD = temp, 
                       trials = "Wei AT",
                       traits = "yield_14__dt_ha",
                     engine = "SpATS",
                      spatial = TRUE,
                       design = "rowcol")
 summary(mymod)

Summary statistics 
==================

Summary statistics for yield_14__dt_ha in Wei AT  

                         yield_14__dt_ha
Number of observations              39.0
Number of missing values             1.0
Mean                              105.62
Median                            106.32
Min                                87.02
Max                               126.32
First quantile                    100.53
Third quantile                    109.12
Variance                          69.291


Estimated heritability 
======================

Heritability: 0.87 

Predicted means (BLUEs & BLUPs) 
===============================
Best 20 genotypes
      BLUEs       SE    BLUPs     SE
15 121.3228   2.7255 119.7414 2.9113
7  118.5933   3.3831 119.3564 3.5331
8  117.6420   2.6008 116.5269 2.8455
4  111.3919   2.8968 112.1268 3.0687
18 111.3896   3.7124 110.4797 3.5163
13 110.8134   2.9583 111.9822 3.0616
20 110.4822   3.0566 110.1084 3.0268
1  110.0335   2.7078 110.4074 2.8360
14 109.3475   2.8923 108.9432 2.8761
3  107.0674   3.2605 109.1607 3.4096
11 106.6985   3.2903 108.5474 3.4453
17 104.6890   3.1384 106.8301 3.3033
16 103.4504   2.7854 104.4838 2.8297
6  103.1571   3.0458 104.3008 3.1777
2  102.5217   3.2179 105.8277 3.2422
5  102.0199   3.0726 103.4392 3.2428
19 101.0795   3.1032 103.3310 3.2278
10  99.5390   3.4511 102.9536 3.5367
9   99.2918   3.3708 101.9147 3.4891
12  90.7225   2.9412  94.6616 3.0635


report(mymod, outfile = "Test.pdf")
Error in createReport(x = modTr, reportName = "modelReport.Rnw", reportPackage = "statgenSTA",  : 
  outfile path cannot contain spaces. Provide a path without spaces or
           a relative path.
report(mymod,
         outfile = tempfile(fileext = ".pdf"),
         what = "fixed")
Error in createReport(x = modTr, reportName = "modelReport.Rnw", reportPackage = "statgenSTA",  : 
  outfile path cannot contain spaces. Provide a path without spaces or
           a relative path.

Best Gregor

**Comment by BartJanvanRossum** [comment]
Thanks for the extra information. It turns out the the space in your trial name causes the error. If I see it correctly you use Wei AT as a trial name. This will work fine when fitting all models and extracting information, however when creating the report the trial name is concatenated to the name of the outfile you provide. The easiest workaround would be to remove the space from the trial name before doing the analysis. 

For the package I will try to find a way around this, possibly by replacing spaces by _ in trial names when creating reports. I will leave this issue open until that is done.

Best Bart-Jan

**Comment by GregorDall** [comment]
Thank you so much for the rapid response, and thank you for the package!

Have a nice weekend! 

Best Gregor

**Comment by BartJanvanRossum** [comment]
This is now fixed in the develop version of the package. That version can be installed directly from github like this:
```r
remotes::install_github("Biometris/statgenSTA", ref = "develop", dependencies = TRUE)
```

**Comment by GregorDall** [comment]
Thank you!
