### ISSUE TITLE
plot.STA and discrete axis scales

### ISSUE THREAD

**Issue by vrangaUQ** [Biometris/statgenSTA#9]
Hi, 
I was recently using plot.STA and discovered that after plotting the spatial analysis, sometimes the colCoord axis scales are continuous (For example: 2.5, 5.0, 7.5 and so on). This would not be ideal as it would be great if we could have it discrete (For example: 4,8,12 and so on). colCoord is already a factor obtained by createTD.

How can I achieve this? I was not sure if this was an issue but I was just wondering if this is something worth looking at to be able to achieve it. It would be great if we could have more control on the scale and the numbers that could be printed. I'll attach an image of the plot for reference. Thank you so much. 

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/a6bbba36-161a-48cc-b638-6c4905889d26">

**Comment by BartJanvanRossum** [comment]
Hi,
Thanks for mentioning this. I was actually already aware of the issue, but it was very low on my "things that have to be fixed" list, since it is not really wrong. I will move it upward a bit and try to figure out if I can come up with a generic solution for how to overwrite the defaults chosen by ggplot by something sensible.

You can achieve this yourself by manually adjusting the x-axis ticks for each of the subplots. Below I made a small example using the example data contained in the package.

```r
library(statgenSTA)

modSp <- fitTD(TD = TDHeat05,
               design = "res.rowcol",
               traits = "yield")

p <- plot(modSp,
          what = "fixed",
          plotType = "spatial", 
          output = FALSE)

p$HEAT05$yield$p1 +
  ggplot2::scale_x_continuous(breaks = c(3, 6, 9))
```

**Comment by BartJanvanRossum** [comment]
This should be fixed now on the develop branch of statgenSTA.
You can install the package from there using:

```r
remotes::install_github("Biometris/statgenSTA", ref = "develop", dependencies = TRUE)
```
